/**
 * Data dump -- prepopulated
 */

 /* rules content */
INSERT INTO `games_threads` (`game_id`, `thread_url`, `thread_title`) VALUES (0, 'http://www.clanaod.net/forums/showthread.php?t=3326', 'AOD Ranking Structure');
INSERT INTO `games_threads` (`game_id`, `thread_url`, `thread_title`) VALUES (0, 'http://www.clanaod.net/forums/showthread.php?t=3327', 'AOD Code of Conduct');
INSERT INTO `games_threads` (`game_id`, `thread_url`, `thread_title`) VALUES (3, 'http://www.clanaod.net/forums/showthread.php?t=68687', 'FF Division Rules and Regulations');
INSERT INTO `games_threads` (`game_id`, `thread_url`, `thread_title`) VALUES (2, 'http://www.clanaod.net/forums/showthread.php?t=74210', 'BF4 Division Rules and Regs');
INSERT INTO `games_threads` (`game_id`, `thread_url`, `thread_title`) VALUES (4, 'http://www.clanaod.net/forums/showthread.php?t=82530', 'GRP Division Rules and Regulations');
INSERT INTO `games_threads` (`game_id`, `thread_url`, `thread_title`) VALUES (2, 'http://www.clanaod.net/forums/showthread.php?t=85737', 'BF4 Ventrilo Rules and Multiclanning');
INSERT INTO `games_threads` (`game_id`, `thread_url`, `thread_title`) VALUES (5, 'http://www.clanaod.net/forums/showthread.php?t=86158', 'JK Vent Rules and Multiclanning');
INSERT INTO `games_threads` (`game_id`, `thread_url`, `thread_title`) VALUES (9, 'http://www.clanaod.net/forums/showthread.php?t=91380', 'WF Division Rules and Regs');
INSERT INTO `games_threads` (`game_id`, `thread_url`, `thread_title`) VALUES (9, 'http://www.clanaod.net/forums/showthread.php?t=91385', 'WF Division Structure');




 /* games content */
INSERT INTO `games` (`id`, `description`, `short_name`, `full_name`, `subforum`) VALUES (1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer in massa at leo vulputate faucibus sed et erat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi ut euismod sem, vitae consectetur ex. Sed porta elit ligula, sed posuere nunc sagittis fermentum. Quisque sed tristique libero. Quisque vehicula ornare ex, eget accumsan velit interdum sed. Ut suscipit iaculis dolor ac efficitur. Duis libero purus, tempus vel egestas at, tristique sit a', 'Arma3', 'Arma 3', 'http://www.clanaod.net/forums/forumdisplay.php?f=464');
INSERT INTO `games` (`id`, `description`, `short_name`, `full_name`, `subforum`) VALUES (2, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer in massa at leo vulputate faucibus sed et erat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi ut euismod sem, vitae consectetur ex. Sed porta elit ligula, sed posuere nunc sagittis fermentum. Quisque sed tristique libero. Quisque vehicula ornare ex, eget accumsan velit interdum sed. Ut suscipit iaculis dolor ac efficitur. Duis libero purus, tempus vel egestas at, tristique sit a', 'BF4', 'Battlefield 4', 'http://www.clanaod.net/forums/forumdisplay.php?f=456');
INSERT INTO `games` (`id`, `description`, `short_name`, `full_name`, `subforum`) VALUES (3, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer in massa at leo vulputate faucibus sed et erat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi ut euismod sem, vitae consectetur ex. Sed porta elit ligula, sed posuere nunc sagittis fermentum. Quisque sed tristique libero. Quisque vehicula ornare ex, eget accumsan velit interdum sed. Ut suscipit iaculis dolor ac efficitur. Duis libero purus, tempus vel egestas at, tristique sit a', 'FF', 'Firefall', 'http://www.clanaod.net/forums/forumdisplay.php?f=441');
INSERT INTO `games` (`id`, `description`, `short_name`, `full_name`, `subforum`) VALUES (4, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer in massa at leo vulputate faucibus sed et erat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi ut euismod sem, vitae consectetur ex. Sed porta elit ligula, sed posuere nunc sagittis fermentum. Quisque sed tristique libero. Quisque vehicula ornare ex, eget accumsan velit interdum sed. Ut suscipit iaculis dolor ac efficitur. Duis libero purus, tempus vel egestas at, tristique sit a', 'GR:P', 'Ghost Recon Phantoms', 'http://www.clanaod.net/forums/forumdisplay.php?f=489');
INSERT INTO `games` (`id`, `description`, `short_name`, `full_name`, `subforum`) VALUES (5, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer in massa at leo vulputate faucibus sed et erat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi ut euismod sem, vitae consectetur ex. Sed porta elit ligula, sed posuere nunc sagittis fermentum. Quisque sed tristique libero. Quisque vehicula ornare ex, eget accumsan velit interdum sed. Ut suscipit iaculis dolor ac efficitur. Duis libero purus, tempus vel egestas at, tristique sit a', 'JK', 'Jedi Knight', 'http://www.clanaod.net/forums/forumdisplay.php?f=122');
INSERT INTO `games` (`id`, `description`, `short_name`, `full_name`, `subforum`) VALUES (6, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer in massa at leo vulputate faucibus sed et erat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi ut euismod sem, vitae consectetur ex. Sed porta elit ligula, sed posuere nunc sagittis fermentum. Quisque sed tristique libero. Quisque vehicula ornare ex, eget accumsan velit interdum sed. Ut suscipit iaculis dolor ac efficitur. Duis libero purus, tempus vel egestas at, tristique sit a', 'PS2', 'Plantside 2', 'http://www.clanaod.net/forums/forumdisplay.php?f=404');
INSERT INTO `games` (`id`, `description`, `short_name`, `full_name`, `subforum`) VALUES (7, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer in massa at leo vulputate faucibus sed et erat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi ut euismod sem, vitae consectetur ex. Sed porta elit ligula, sed posuere nunc sagittis fermentum. Quisque sed tristique libero. Quisque vehicula ornare ex, eget accumsan velit interdum sed. Ut suscipit iaculis dolor ac efficitur. Duis libero purus, tempus vel egestas at, tristique sit a', 'WT', 'War Thunder', 'http://www.clanaod.net/forums/forumdisplay.php?f=427');
INSERT INTO `games` (`id`, `description`, `short_name`, `full_name`, `subforum`) VALUES (8, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer in massa at leo vulputate faucibus sed et erat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi ut euismod sem, vitae consectetur ex. Sed porta elit ligula, sed posuere nunc sagittis fermentum. ', 'AA', 'Archeage', 'http://www.clanaod.net/forums/forumdisplay.php?f=497');
INSERT INTO `games` (`id`, `description`, `short_name`, `full_name`, `subforum`) VALUES (9, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer in massa at leo vulputate faucibus sed et erat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi ut euismod sem, vitae consectetur ex. Sed porta elit ligula, sed posuere nunc sagittis fermentum. Quisque sed tristique libero. Quisque vehicula ornare ex, eget accumsan velit interdum sed. Ut suscipit iaculis dolor ac efficitur. Duis libero purus, tempus vel egestas at, tristique sit a', 'WF', 'Warframe', 'http://www.clanaod.net/forums/forumdisplay.php?f=511');
